//! Shadcn-inspired reusable primitives implemented with Dioxus 0.7 signals and the shared `shadcn.css`.
//! Each component mirrors the styling and API conventions of the upstream React components while
//! remaining idiomatic to Rust and Dioxus.

mod accordion;
mod alert;
mod avatar;
mod badge;
mod breadcrumb;
mod button;
mod card;
mod checkbox;
mod command;
mod context_menu;
mod dialog;
mod dropdown_menu;
mod hover_card;
mod input;
mod label;
mod menubar;
mod navigation_menu;
mod pagination;
mod popover;
mod progress;
mod radio_group;
mod select;
mod separator;
mod sheet;
mod sidebar;
mod slider;
mod steps;
mod switch;
mod tabs;
mod textarea;
mod toast;
mod tooltip;

pub use accordion::*;
pub use alert::*;
pub use avatar::*;
pub use badge::*;
pub use breadcrumb::*;
pub use button::*;
pub use card::*;
pub use checkbox::*;
pub use command::*;
pub use context_menu::*;
pub use dialog::*;
pub use dropdown_menu::*;
pub use hover_card::*;
pub use input::*;
pub use label::*;
pub use menubar::*;
pub use navigation_menu::*;
pub use pagination::*;
pub use popover::*;
pub use progress::*;
pub use radio_group::*;
pub use select::*;
pub use separator::*;
pub use sheet::*;
pub use sidebar::*;
pub use slider::*;
pub use steps::*;
pub use switch::*;
pub use tabs::*;
pub use textarea::*;
pub use toast::*;
pub use tooltip::*;
