//! Shadcn-inspired reusable primitives implemented with Dioxus 0.7 signals and the shared `shadcn.css`.
//! Each component mirrors the styling and API conventions of the upstream React components while
//! remaining idiomatic to Rust and Dioxus.

mod utils;

mod accordion;
mod alert;
mod aspect_ratio;
mod avatar;
mod badge;
mod breadcrumb;
mod button;
mod calendar;
mod card;
mod checkbox;
mod collapsible;
mod combobox;
mod command;
mod context_menu;
mod date_range_picker;
mod dialog;
mod dropdown_menu;
mod file_drop_zone;
mod form_field;
mod hover_card;
mod input;
mod label;
mod menubar;
mod navigation_menu;
mod pagination;
mod popover;
mod progress;
mod radio_group;
mod scroll_area;
mod select;
mod separator;
mod sheet;
mod sidebar;
mod skeleton;
mod slider;
mod steps;
mod switch;
mod table;
mod tabs;
mod textarea;
mod toast;
mod toggle;
mod toggle_group;
mod tooltip;

pub use accordion::*;
pub use alert::*;
pub use aspect_ratio::*;
pub use avatar::*;
pub use badge::*;
pub use breadcrumb::*;
pub use button::*;
pub use calendar::*;
pub use card::*;
pub use checkbox::*;
pub use collapsible::*;
pub use combobox::*;
pub use command::*;
pub use context_menu::*;
pub use date_range_picker::*;
pub use dialog::*;
pub use dropdown_menu::*;
pub use file_drop_zone::*;
pub use form_field::*;
pub use hover_card::*;
pub use input::*;
pub use label::*;
pub use menubar::*;
pub use navigation_menu::*;
pub use pagination::*;
pub use popover::*;
pub use progress::*;
pub use radio_group::*;
pub use scroll_area::*;
pub use select::*;
pub use separator::*;
pub use sheet::*;
pub use sidebar::*;
pub use skeleton::*;
pub use slider::*;
pub use steps::*;
pub use switch::*;
pub use table::*;
pub use tabs::*;
pub use textarea::*;
pub use toast::*;
pub use toggle::*;
pub use toggle_group::*;
pub use tooltip::*;
